# Main menu configuration

[[source]]
name = "fmiwms"
type = "wms"
url = "http://wms.fmi.fi/fmi-apikey/{APIKEY}/geoserver/"
tileCapabilities = "http://wms.fmi.fi/fmi-apikey/{APIKEY}/geoserver/gwc/service/wmts?request=GetCapabilities"
timeCapabilities = "http://wms.fmi.fi/fmi-apikey/{APIKEY}/geoserver/wms?request=GetCapabilities&service=WMS"
default = true
server = "geoserver"

[[source]]
name = "fmidaliwms"
type = "wms"
url = "http://data.fmi.fi/fmi-apikey/{APIKEY}/"
timeCapabilities = "http://data.fmi.fi/fmi-apikey/{APIKEY}/wms?request=GetCapabilities&service=WMS"
tileCapabilities = "http://data.fmi.fi/fmi-apikey/{APIKEY}/wms?request=GetCapabilities&service=WMS"
server = "smartmet"

[[menu]]
title = "Tutka"
type = "obs"
file = "radar.toml"

[[menu]]
title = "Satelliitti"
type = "obs"
file = "satellite.toml"

[[menu]]
title = "Ennusteet"
type = "for"
file = "forecasts.toml"

[[menu]]
title = "J채채kartta"
type = "obs"
file = "icecoverage.toml"

[[menu]]
title = "ECMWF"
file = "ecmwf.toml"

[[menu]]
title = "PAL"
file = "pal.toml"

[[menu]]
title = "PAL testieditointi"
file = "pal_test.toml"

[[menu]]
title = "Helmi"
file = "helmi.toml"

[[menu]]
title = "HBM"
file = "hbm.toml"

[[menu]]
title = "Ties채채"
file = "tiesaa.toml"

[[menu]]
title = "MST"
file = "mst.toml"

[[menu]]
title = "Harmonie"
file = "harmonie.toml"
