[[item]]

title = "Eurooppa HRV-IR"
layer = "Satellite:eurooppa_hrv-ir_eureffin"

[[item]]

title = "Eurooppa HRV"
layer = "Satellite:eurooppa_hrv_eureffin"

[[item]]
title = "Europe avhrr IR 10.8Âµ"
layer = "Satellite:europe_avhrr_ir108"
